### ISSUE TITLE
allow using both syntaxes for YAML array keys in VIRTUAL_HOST

### ISSUE THREAD

**Issue by xarem** [whatwedo/dde#22]
normally, we use this synax:

```
    storage:
        container_name: example-storage
        image: minio/minio:RELEASE.2022-01-08T03-11-54Z
        environment:
            - VIRTUAL_HOST=storage.example.test
```

if we use this array syntax, the certificate wont be generated becuase we use a grep for `VIRTUAL_HOST=`

https://github.com/whatwedo/dde/blob/master/commands/project/up.sh#L17

```
    storage:
        container_name: example-storage
        image: minio/minio:RELEASE.2022-01-08T03-11-54Z
        environment:
            VIRTUAL_HOST: 'storage.example.test'
```

We should use YQ to read the environment variables.
