### ISSUE TITLE
Ports in conflict, no way to overwrite them with docker-compose.override.yml

### ISSUE THREAD

**Issue by renestalder** [whatwedo/dde#86]
When dde System containers have ports in conflict with other programs, there is currently no way to change them with `docker-compose.override.yml` due to the nature how the YAML arrays will be merged in this case.

The only solution in case of port conflicts, is to either kill the software that is using the same port as the dde service (not possible in my case), or to deactivate the dde system service all together with following lines in the `docker-compose.override.yml`:

_Example for Mailcrab_:

```yml
services:
    mailcrab:
        deploy:
            replicas: 0 # disables mailcrab as port is in conflict with protonmail bridge
```

According to other people, the PR https://github.com/whatwedo/dde/pull/38 might make that possible, but is stale since a while ago.
